Repository martin226/sensai, pull requests merged in 2022-05, with the labels that each got.

#3 feat: website project setup
  .github/semantic.yml
  .github/workflows/website.yml
  website/.eslintrc.js
  website/.gitignore
  website/.husky/commit-msg
  website/.husky/common.sh
  website/.husky/pre-commit
  website/.prettierignore
  website/.prettierrc
  website/README.md
  website/commitlint.config.js
  website/nuxt.config.js
  website/package.json
  website/pages/index.vue
  website/static/favicon.ico
  website/store/README.md
  website/stylelint.config.js
  website/tsconfig.json
  website/windi.config.ts
  website/yarn.lock
Labels: enhancement

#4 feat: backend setup
  .github/workflows/backend.yml
  .gitignore
  backend/backend/__init__.py
  backend/poetry.lock
  backend/pyproject.toml
Labels: enhancement

#6 feat: landing page
  vetur.config.js
  website/components/Landing/Hero.vue
  website/pages/index.vue
  website/windi.config.ts
Labels: enhancement

#7 feat: api authentication
  backend/backend/__init__.py
  backend/backend/database.py
  backend/backend/routes/auth.py
  backend/poetry.lock
  backend/pyproject.toml
Labels: enhancement

#9 feat: authentication pages
  website/assets/img/sensai.svg
  website/components/Auth/Login.vue
  website/components/Auth/Register.vue
  website/components/Icon/Eye.vue
  website/components/Icon/EyeOff.vue
  website/nuxt.config.js
  website/package.json
  website/pages/login.vue
  website/pages/register.vue
  website/store/index.js
  website/tsconfig.json
  website/windi.config.ts
  website/yarn.lock
Labels: enhancement

#12 feat: workout list
  backend/backend/__init__.py
  backend/backend/routes/workout.py
Labels: enhancement

#14 feat: get workouts
  backend/backend/routes/workout.py
Labels: enhancement

#16 feat: dashboard
  website/components/Shared/Footer.vue
  website/components/Shared/Navbar.vue
  website/components/Workout/Card.vue
  website/pages/dashboard.vue
Labels: enhancement

#18 feat: finish workout routes
  backend/backend/routes/workout.py
Labels: enhancement

#20 feat: backend AI route
  backend/backend/__init__.py
  backend/backend/ai.py
  backend/poetry.lock
  backend/pyproject.toml
Labels: enhancement

#23 docs: update README.md
  README.md
  docs/logo.png
Labels: documentation

#26 fix: workout route bugs
  backend/backend/routes/workout.py
Labels: bug

#27 feat: workout info screen
  backend/backend/routes/workout.py
  website/components/Workout/Coach.vue
  website/components/Workout/Info.vue
  website/components/Workout/Summary.vue
  website/package.json
  website/pages/workout/_id.vue
  website/yarn.lock
Labels: enhancement
